version: '3.8'
services:
  app:
    container_name: qlik-script-effort-analyzer
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/usr/src/app/.env
      - ./schema.json:/usr/src/app/schema.json
      - ./sent-requests:/usr/src/app/sent-requests
      - ./received-requests:/usr/src/app/received-requests
  proxy:
    container_name: proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /home/qmi/common/qmicerts:/certs

