version: '3.8'
services:
  app:
    container_name: qlik-script-effort-analyzer
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/usr/src/app/.env
      - ./schema.json:/usr/src/app/schema.json
